### ISSUE TITLE
Make Admin panel

### ISSUE THREAD

**Issue by KilliBruhh** [KilliBruhh/DecoderMM#3]
- Let users add there own Codes and documents

**Comment by KilliBruhh** [comment]
### What?

- Way so users can add there own codes without the dev's help
- Currently you acces the panel by entering the code `Admin1` (Will change)

### TODO

- [ ] Show All codes
- [ ] Add / Delete code
- [ ] Edit Code
- [ ] better way to navigate to admin panel
